### ISSUE TITLE
Evaluate first round of metro hard fork 

### ISSUE THREAD

**Issue by realcodywburns** [ethereumproject/EIPs#79]
The first ETH Hard fork in the metropolis fork will be the Byzantium release. will contain the following, however, not all are applicable to ETC:

- [ ]  EIP-100 Change difficulty adjustment to target mean block time including uncles | #916
- [ ]  EIP-206 REVERT instruction in the Ethereum Virtual Machine | #918
- [ ]  EIP-213 Precompiled contracts for addition and scalar multiplication on the elliptic curve alt_bn128 | #924
- [ ]  EIP-212 Precompiled contract for pairing check
- [ ]  EIP-198 Precompiled contract for bigint modular exponentiation | #920
- [ ]  EIP-211 New opcodes: RETURNDATASIZE and RETURNDATACOPY | #919
- [ ]  EIP-214 New opcode STATICCALL | #922
- [ ]  EIP-649 Metropolis Difficulty Bomb Delay and Issuance Reduction
- [ ]  EIP-658 Embedding transaction return data in receipts
- [ ]  EIP-684 Prevent overwriting contracts

A section has been added to the wiki page to indicate support of proposals

https://github.com/ethereum/ethereumj/issues/923

**Comment by sorpaas** [comment]
Already under discussions are:

* ECIP-1025 #66: derived from EIP-212 and EIP-213. ECIP-1035 #78 (needs to be combined with others) is a competing ECIP with this.
* ECIP-1026 #67: derived from EIP-198.

EIP-649 does not apply to ETC chain.

The hard fork support wiki page is at https://github.com/ethereumproject/ECIPs/wiki/Hard-Fork-Support. Please create a new ECIP (if not already existing) to accommodate discussions within the community if you prefer some of the above EIPs.

**Comment by sorpaas** [comment]
Recent Solidity changes have broken Ethereum Classic because it uses `RETURNDATASIZE`/`RETURNDATACOPY` and possibly others. Here's an example: https://github.com/paritytech/parity/issues/8503

Just a reminder that ETC community would probably want to:
* Maintain an older version of Solidity.
* Or speed up this issue and adopt necessary Byzantium hard forks.

**Comment by realcodywburns** [comment]
Closing, this repo is depreciated . To be reopened on http://github.com/ethereumclassic/ECIPs
